### ISSUE TITLE
Custom shader support

### ISSUE THREAD

**Issue by markandgo** [mausimus/ShaderGlass#19]
Will there be any chance for importing our own shaders like the ones written for shadertoy?

**Comment by rohatsu** [comment]
Yes that's on my list, although there's two things here:
* ability to compile and load a custom shader; currently this requires running ShaderGen to generate .h format and then recompiling ShaderGlass - I'd like to change it so that it's possible to compile into a standalone file which can be loaded from ShaderGlass menu
* supporting other shader formats than RetroArch (for example shadertoy or reshade) - either by using a converter into .slangp (there might be some out there already) or by adding new back-ends into ShaderGlass (quite a lot of work potentially)

**Comment by Lucide** [comment]
Is a pre-built version of ShaderGen available?

**Comment by ThatOtherAndrew** [comment]
Is there any update on this by any chance, or is it still to be planned?

**Comment by markandgo** [comment]
I discovered ShaderGlass can be used with Reshade so I no longer have to wish for custom shader support.
