### ISSUE TITLE
Ctrl+Shift+S is unfortunate choice for screenshot.

### ISSUE THREAD

**Issue by ythoimust** [mausimus/ShaderGlass#44]
ShaderGlass and its choice of ctrl+shift+s is rather unfortunate. That shortcut is used by all sort of software as "save as" but now instead I get snapshot. Since ShaderGlass is an overlay software it cannot just hijack crucial hotkeys. So some way to modify hotkeys would be nice.

**Comment by skeddles** [comment]
Since it seems to disable itself when you try to take a screenshot normally, perhaps they could do ctrl+printscreen or something to force taking a screenshot.

Ideally you could change the hotkeys and allow normal screenshots to include the CRT view

**Comment by mausimus** [comment]
Thanks, I'll add some options to enable/disable or possibly change the screenshot hotkey. I won't be able to make Windows default screenshot capture ShaderGlass window in Glass mode since that's how it achieves the transparency effect (should work in Window mode).

**Comment by PiorGit** [comment]
Hello,
This might not seem like much, but indeed this screenshot hotkey really gets in the way. My practical case is as follows :

I am using Shaderglass to duplicate (and flip, and downres/blur) my current working document in Photoshop. The Shaderglass Ctrl Shift S screenshot hotkey is conflicting with my Photoshop Save As hotkey. As a matter of fact I am writing this as I just got the case right now : I was meaning to save out a document which just happened require PNG as a format, and without realizing it I saved a ShaderGlass screenshot instead. I am glad I caught it before closing Photoshop, otherwise I would have lost some work.

I understand that this is an edge case but it literally caused me to not save something I was meaning to save. As far as I am concerned I'd be happy with a custom build with the screenshot feature disabled, or even all hotkeys removed altogether as the risk of triggering a Shaderglass hotkey while working is just too high.

I hope this makes sense.

**Comment by PiorGit** [comment]
By the way - I should also probably mention that the very issue with this hotkey is that unlike the other ones (like Next Shader, Random), it gets triggered even when ShaderGlass isn't in focus (and the same goes for the Fullscreen hotkey).

Now I can understand this design/reasoning when ShaderGlass is being used for gaming, but I feel like a better design would consist of letting the user define their shortcuts, and letting them decide if a given shortcut is supposed to be global (= working even when the SG window isn't in focus) on a per-hotkey basis with a tickbox.

**Comment by mausimus** [comment]
Added option to disable global hotkeys in 0.8
